<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageContentSeeder extends Seeder
{
    public function run(): void
    {
        $contents = [

            // ══════════════════════════════════════════
            // HOME PAGE
            // ══════════════════════════════════════════
            [
                'page'      => 'home',
                'section'   => 'hero',
                'title'     => 'DBillers - The Medical Billing Partner',
                'subtitle'  => 'Smart RCM for US Healthcare Providers. We aren\'t just a service; we are "The" Doctor Billers',
                'content'   => '<p>In an industry of "good enough" we choose to be The standard. DBillers (The Doctor Billers) treats your revenue cycle with the same clinical precision you apply to your patients.<br><br>We bridge the gap between complex US healthcare regulations and your bottom line. By integrating expert Coding, seamless Credentialing, and proactive AR recovery, we don\'t just process claims - we optimize your entire practice\'s financial health.<br><br>Stop just billing. Start leading.</p>',
                'image_url' => 'page-images/01KQX5S5GSVECSMYXV9JFT985T.jpg',
                'metadata'  => '{"buttons": [{"text": "Book a Free Consultation", "url": "/contact", "icon": "fa-arrow-right"}, {"text": "Free Billing Demo", "url": "/contact", "icon": "fa-calendar-alt"}], "trust_badges": ["1500+ Satisfied Providers", "75+ Specialties Served", "1200+ Billing & Coding Experts"], "floating_icon": "fa-chart-line", "meta_title": "Medical Billing & RCM Services | DBillers for US Healthcare", "meta_description": "Maximize revenue with DBillers, the precision billing platform for modern medicine. Specialized RCM, coding, and denial management for US doctors. Get a free consultation.", "meta_keywords": "medical billing services, revenue cycle management, RCM company, claim denial management, medical coding services, healthcare billing solutions", "og_title": "Medical Billing & RCM Services | DBillers", "og_description": "Maximize your practice revenue with DBillers. Specialized medical billing and revenue cycle management for US healthcare providers."}',
                'order'     => 1,
            ],
            [
                'page'      => 'home',
                'section'   => 'services_overview',
                'title'     => 'Overview of Medical Billing Services in the USA',
                'subtitle'  => null,
                'content'   => 'Medical billing services provide organized solutions that convert clinical data into billable insurance claims.',
                'image_url' => null,
                'metadata'  => '{"services":[{"title":"Medical Billing Consultation","description":"Expert patient billers handle check-in\/out, claims, payments, and denials.","icon":"fa-headset","link":"\/contact"},{"title":"Medical Coding","description":"Clinical coding officers translate patient services into ICD-10 and CPT codes.","icon":"fa-code","link":"\/contact"},{"title":"Provider Credentialing","description":"Credentialing specialists help providers join desirable payer networks.","icon":"fa-id-card","link":"\/contact"},{"title":"Healthcare RCM","description":"Specialty-specific revenue cycle management with a dedicated biller.","icon":"fa-chart-pie","link":"\/contact"}]}',
                'order'     => 2,
            ],
            [
                'page'      => 'home',
                'section'   => 'medical_claims',
                'title'     => 'We Boost Healthcare Income with Quick, Uncut Reimbursements',
                'subtitle'  => 'The Billing Firm That Does Medical Claims Processing',
                'content'   => 'Claim management can be difficult when you need timely submissions and full payment.',
                'image_url' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=500&h=400&fit=crop',
                'metadata'  => '{"features":[{"title":"Secure Claim Data Transmission","description":"Safest digital encryption protects sensitive patient data.","icon":"fa-shield-alt"},{"title":"Increase Revenue","description":"Get full payments without unfair insurance network cuts.","icon":"fa-chart-line"},{"title":"Instant Claim Submission","description":"Electronic billing service files claims instantly.","icon":"fa-bolt"},{"title":"Claim Follow-Up & Resolution","description":"Denied claims are appealed and reprocessed successfully.","icon":"fa-clock"}],"button_text":"Book Free Consultation","button_link":"\/contact"}',
                'order'     => 3,
            ],
            [
                'page'      => 'home',
                'section'   => 'specialized_agency',
                'title'     => 'When "Good Enough" Isn\'t Enough, You Need a Specialized Medical Billing Agency',
                'subtitle'  => null,
                'content'   => 'As a leading billing provider, we extract every possible dollar from your claims through 24/7 billing cycle oversight.',
                'image_url' => null,
                'metadata'  => '{"button_text":"Yes, I Want a Free Billing Demo","button_link":"\/contact"}',
                'order'     => 4,
            ],
            [
                'page'      => 'home',
                'section'   => 'trust_ratings',
                'title'     => 'Trust Your Billing to a Company Ranked Among the Best',
                'subtitle'  => null,
                'content'   => 'With a 4.8-star Trustpilot rating from 200+ reviews, a 4.8-star Google rating from 340+ reviews, and an A+ Better Business Bureau rating.',
                'image_url' => null,
                'metadata'  => '{"stats":[{"value":"Almost 99%","label":"Clean Claim Ratio"},{"value":"About 97.35%","label":"First Submission Pass Rate"},{"value":"Up to 30%","label":"Revenue Increase"}]}',
                'order'     => 5,
            ],
            [
                'page'      => 'home',
                'section'   => 'tech_expertise',
                'title'     => 'Medical Billing That Unites Technology & Expertise to Meet Every Doctor\'s Vision',
                'subtitle'  => null,
                'content'   => 'Our USA-based revenue cycle management company helps individual and institutional providers navigate patient billing and coding challenges.',
                'image_url' => null,
                'metadata'  => '{"tags":["Patient Verification","Claim Scrubbing","Claim Submission","Revenue Cycle Management","A\/R Recovery","Fast Reimbursement"],"cards":[{"icon":"fa-smile","value":"96%","title":"Happiness Score","description":"Based on 4.8-star rating from 350+ providers"},{"icon":"fa-users","value":"1,200+","title":"Billing Experts","description":"CMRS, RHIA, CPB certified billers"}],"button_text":"About Us","button_link":"\/about"}',
                'order'     => 6,
            ],
            [
                'page'      => 'home',
                'section'   => 'pricing_offer',
                'title'     => 'Experience Our Medical Billing Services for as Low as 2.49%',
                'subtitle'  => null,
                'content'   => 'Over 1,500 medical practices trust DBillers. Let\'s have a chat.',
                'image_url' => null,
                'metadata'  => '{"features":[{"icon":"fa-shield-alt","text":"Patient insurance coverage verification on the spot"},{"icon":"fa-lock","text":"HIPAA-compliant billing for data safety"},{"icon":"fa-clock","text":"24\/7 medical billing to handle every claim submission"},{"icon":"fa-chart-line","text":"98% claim reimbursement rate for healthy cash flow"}],"button_text":"Book a Demo","button_link":"\/contact"}',
                'order'     => 7,
            ],
            [
                'page'      => 'home',
                'section'   => 'dedicated_team',
                'title'     => 'Dedicated Accounts Managers & Expert Medical Billers for Health Centers',
                'subtitle'  => null,
                'content'   => 'Healthcare organizations are at the heart of our billing and collections team.',
                'image_url' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&h=400&fit=crop',
                'metadata'  => '{"button_text":"Claim Free Practice Audit","button_link":"\/contact"}',
                'order'     => 8,
            ],
            [
                'page'      => 'home',
                'section'   => 'provider_challenges',
                'title'     => 'Which of These Challenges Are You Facing as a Provider?',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"challenges":["Inadequate follow-up on claims and payments","Accounts receivable aging past 90\/120+ days","Rising patient balances causing financial strain","Frustration due to lack of transparency and reporting","Overall decline in collections impacting practice revenue"]}',
                'order'     => 9,
            ],
            [
                'page'      => 'home',
                'section'   => 'specialty_billing',
                'title'     => 'Specialty Medical Billing',
                'subtitle'  => null,
                'content'   => 'Our tailored billing services boost reimbursements through specialty-focused teams.',
                'image_url' => null,
                'metadata'  => '{"specialties":["Laboratory Billing","Cardiology","Behavioral Health","Orthopedics","Urgent Care","Urology"]}',
                'order'     => 10,
            ],
            [
                'page'      => 'home',
                'section'   => 'nationwide',
                'title'     => 'Nationwide Availability',
                'subtitle'  => null,
                'content'   => 'As a top medical billing company in the USA, DBillers helps providers succeed financially across all 50 states.',
                'image_url' => null,
                'metadata'  => '{"locations":["Chicago","Los Angeles","Alabama","California","Indiana","New York"]}',
                'order'     => 11,
            ],
            [
                'page'      => 'home',
                'section'   => 'pricing_comparison',
                'title'     => 'Affordable Pricing vs. In-House Billing',
                'subtitle'  => null,
                'content'   => 'Save compared to internal billing with our affordable 2.49% collections rate.',
                'image_url' => null,
                'metadata'  => '{"included":["Billing Software","Denial Management","Accounts Management","Electronic Statements","Clearinghouse Services","1:1 Technical Support"],"button_text":"Get Instant Free Pricing Quote","button_link":"\/contact"}',
                'order'     => 12,
            ],
            [
                'page'      => 'home',
                'section'   => 'testimonials',
                'title'     => 'See What Healthcare Providers Say About Us',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"testimonials":[{"stars":4.5,"text":"DBillers responds to my inquiries within hours, not days.","author":"David J. Gel***","role":"Chiropractor"},{"stars":5,"text":"We are more than satisfied with DBillers.","author":"Dr. Gennaya Matt***","role":"Plastic Surgeon"},{"stars":5,"text":"DBillers has been a phenomenal asset to our company.","author":"Dr. Mike Lan***","role":"Internal Medicine Specialist"},{"stars":5,"text":"My Behavioral Health practice has experienced great improvement.","author":"Dr. Belen Bur***","role":"Psychiatrist"}],"trust_badge":"Trusted by 300+ Verified Practices","rating":"4.8\/5","reviews":"354"}',
                'order'     => 13,
            ],
            [
                'page'      => 'home',
                'section'   => 'faq',
                'title'     => 'Frequently Asked Questions',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"faqs":[{"question":"What is a medical billing company?","answer":"For a medical practice, billing services handle the logistical details of getting paid by insurance companies and patients."},{"question":"What is a medical billing service?","answer":"Medical billing services manage every financial touchpoint after a patient visit."},{"question":"What services does your company offer?","answer":"We offer provider enrollment, insurance verification, charge entry, claim submission, payment posting, accounts receivable management, denial management, appeal management, patient billing, reimbursement tracking, and collections."},{"question":"How does your company handle claim reimbursement?","answer":"Accurate claim submission is only the beginning. We communicate with payers to shepherd each claim to resolution."},{"question":"Can I monitor the performance?","answer":"Yes. DBillers lets providers track the caliber and results of their facility\'s billing."},{"question":"Do you offer advanced medical billing services?","answer":"Yes. We have the people and processes to provide specialized billing for Medicaid and Medicare patients."}]}',
                'order'     => 14,
            ],
            [
                'page'      => 'home',
                'section'   => 'final_cta',
                'title'     => 'Schedule a Free Demo',
                'subtitle'  => 'Sign up and book a free service demo',
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"buttons":[{"text":"Free Demo","link":"\/contact"},{"text":"See Pricing Packages","link":"\/contact"}]}',
                'order'     => 15,
            ],

            // ══════════════════════════════════════════
            // ABOUT PAGE
            // ══════════════════════════════════════════
            [
                'page'      => 'about',
                'section'   => 'hero',
                'title'     => 'About DBillers',
                'subtitle'  => 'Trusted Medical Billing Partner for Healthcare Providers Across America',
                'content'   => 'We are a US-based medical billing company dedicated to helping physicians, clinics, and hospitals maximize revenue.',
                'image_url' => null,
                'metadata'  => '{"button_text": "Meet Our Team", "button_link": "#team", "meta_title": "About DBillers | Medical Billing Experts for US Healthcare Providers", "meta_description": "Learn about DBillers, a leading medical billing company helping healthcare providers maximize revenue with expert RCM services since 2015. Trusted by 1500+ providers.", "meta_keywords": "about DBillers, medical billing company, RCM services, healthcare billing experts, revenue cycle management company", "og_title": "About DBillers | Medical Billing Experts", "og_description": "Trusted medical billing experts helping US healthcare providers maximize revenue since 2015."}',
                'order'     => 1,
            ],
            [
                'page'      => 'about',
                'section'   => 'our_story',
                'title'     => 'Our Story',
                'subtitle'  => null,
                'content'   => 'DBillers was founded with a simple mission: help healthcare providers get paid fairly and quickly for the care they deliver.',
                'image_url' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&h=400&fit=crop',
                'metadata'  => '{"stats":[{"value":"2015","label":"Founded"},{"value":"1,200+","label":"Billing Experts"},{"value":"1,500+","label":"Providers"}]}',
                'order'     => 2,
            ],
            [
                'page'      => 'about',
                'section'   => 'mission',
                'title'     => 'Our Mission & Values',
                'subtitle'  => null,
                'content'   => 'To empower healthcare providers with transparent, efficient, and results-driven medical billing.',
                'image_url' => null,
                'metadata'  => '{"values":[{"icon":"fa-shield-alt","title":"Integrity","description":"We bill honestly, communicate clearly, and never hide fees."},{"icon":"fa-graduation-cap","title":"Expertise","description":"Continuous training ensures our team knows the latest coding rules."},{"icon":"fa-chalkboard-user","title":"Accountability","description":"We take ownership of your revenue cycle."},{"icon":"fa-handshake","title":"Partnership","description":"Your success is our success."}]}',
                'order'     => 3,
            ],
            [
                'page'      => 'about',
                'section'   => 'team',
                'title'     => 'The Experts Behind Your Billing',
                'subtitle'  => null,
                'content'   => 'Our team includes certified professionals who live and breathe medical billing.',
                'image_url' => null,
                'metadata'  => '{"stats":[{"value":"1,200+","label":"Certified Billers"},{"value":"75+","label":"Specialties"},{"value":"24\/7","label":"Support"},{"value":"98%","label":"Retention"}],"button_text":"View Credentials","button_link":"\/contact"}',
                'order'     => 4,
            ],
            [
                'page'      => 'about',
                'section'   => 'why_choose',
                'title'     => 'Why Over 1,500 Providers Trust Us',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"reasons":["Pay-for-paid pricing model","No long-term contracts","Free EHR software included","US-based support team","99% clean claim ratio","30% average revenue increase","Dedicated account manager","Transparent monthly reporting"]}',
                'order'     => 5,
            ],
            [
                'page'      => 'about',
                'section'   => 'approach',
                'title'     => 'How We Work',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"steps":[{"number":"1","title":"Onboarding","description":"We learn your practice workflow, software, and specialty needs."},{"number":"2","title":"Integration","description":"We connect with your EHR or provide our free billing software."},{"number":"3","title":"Execution","description":"Our team handles coding, claims, follow-up, and denials daily."},{"number":"4","title":"Optimization","description":"We review reports monthly and fine-tune for better results."}]}',
                'order'     => 6,
            ],
            [
                'page'      => 'about',
                'section'   => 'certifications',
                'title'     => 'Certifications & Industry Recognition',
                'subtitle'  => 'We maintain the highest standards in medical billing and data security.',
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"badges":["HIPAA Compliant","A+ BBB Rated","4.8\/5 Google Rating","4.8\/5 Trustpilot Rating"],"trust_text":"\u2b50 Rated 4.8 stars by over 350 verified providers"}',
                'order'     => 7,
            ],
            [
                'page'      => 'about',
                'section'   => 'final_cta',
                'title'     => 'Start Your Journey With DBillers Today',
                'subtitle'  => 'Join hundreds of providers who have improved their revenue cycle.',
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"buttons":[{"text":"Schedule Free Demo","link":"\/contact"},{"text":"Contact Us","link":"\/contact"}]}',
                'order'     => 8,
            ],

            // ══════════════════════════════════════════
            // SERVICES PAGE
            // ══════════════════════════════════════════
            [
                'page'      => 'services',
                'section'   => 'hero',
                'title'     => 'Medical Billing Services',
                'subtitle'  => 'Comprehensive Revenue Cycle Management for Healthcare Providers',
                'content'   => 'We offer end-to-end medical billing and coding solutions for physicians, clinics, and hospitals across the USA.',
                'image_url' => null,
                'metadata'  => '{"button_text": "Book a Free Consultation", "button_link": "\/contact", "meta_title": "Medical Billing & Coding Services | RCM Solutions | DBillers", "meta_description": "Comprehensive medical billing services including coding, claim submission, denial management, and RCM. Maximize your practice revenue with DBillers. Free consultation.", "meta_keywords": "medical billing services, medical coding, claim submission, denial management services, AR recovery specialists, RCM solutions", "og_title": "Medical Billing & Coding Services | DBillers", "og_description": "End-to-end RCM solutions: coding, claims, denial management, and AR recovery for US healthcare providers."}',
                'order'     => 1,
            ],
            [
                'page'      => 'services',
                'section'   => 'core_services',
                'title'     => 'What We Do',
                'subtitle'  => null,
                'content'   => "Every practice is different. That's why we offer flexible, specialty-specific billing services.",
                'image_url' => null,
                'metadata'  => '{"services":[{"icon":"fa-chart-line","title":"Medical Billing Consultation","description":"Our expert billers manage the complete billing cycle for your practice.","link":"\/contact"},{"icon":"fa-code","title":"Medical Coding","description":"Certified clinical coders translate patient services into accurate ICD-10 and CPT codes.","link":"\/contact"},{"icon":"fa-id-card","title":"Provider Credentialing","description":"Getting enrolled with insurance networks can take months.","link":"\/contact"},{"icon":"fa-chart-pie","title":"Healthcare Revenue Cycle Management","description":"RCM is the big picture. We assign a dedicated biller to your practice.","link":"\/contact"},{"icon":"fa-file-invoice","title":"Medical Claims Processing","description":"Claims management is where most practices lose money.","link":"\/contact"},{"icon":"fa-envelope-open-text","title":"Denial Management & A\/R Recovery","description":"Denied claims don\'t have to mean lost revenue.","link":"\/contact"}]}',
                'order'     => 2,
            ],
            [
                'page'      => 'services',
                'section'   => 'why_different',
                'title'     => 'What Makes Our Billing Services Different',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => 'page-images/01KQX8JQPV7SF52G2ZBQ1TD98Q.png',
                'metadata'  => '{"reasons":["Pay-for-paid model \u2013 We only get paid when you get paid","No long-term contracts \u2013 Month-to-month flexibility","Free EHR software \u2013 Included with our billing services","24\/7 claim monitoring \u2013 We work round the clock","US-based team \u2013 Local support, no offshore handoffs","Transparent reporting \u2013 Real-time dashboard access"]}',
                'order'     => 3,
            ],
            [
                'page'      => 'services',
                'section'   => 'features',
                'title'     => "What's Included With Every Service",
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"features":[{"icon":"fa-shield-alt","title":"Secure Data Transmission","description":"Safest digital encryption protects sensitive patient information."},{"icon":"fa-bolt","title":"Instant Claim Submission","description":"Electronic billing files claims within hours, not days."},{"icon":"fa-clock","title":"Claim Follow-Up & Resolution","description":"Denied claims are appealed and reprocessed successfully."},{"icon":"fa-headset","title":"Dedicated Account Manager","description":"One point of contact who knows your practice inside out."}]}',
                'order'     => 4,
            ],
            [
                'page'      => 'services',
                'section'   => 'pricing',
                'title'     => 'Simple, Transparent Pricing',
                'subtitle'  => 'Our rates start as low as 2.49% of collections. No hidden fees.',
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"savings_text":"Save 30-40%","savings_subtext":"compared to in-house billing","button_text":"Get Instant Pricing Quote","button_link":"\/contact"}',
                'order'     => 5,
            ],
            [
                'page'      => 'services',
                'section'   => 'final_cta',
                'title'     => 'Ready to Improve Your Revenue Cycle?',
                'subtitle'  => 'Join over 1,500 providers who trust DBillers with their medical billing.',
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"buttons":[{"text":"Schedule Free Demo","link":"\/contact"},{"text":"Contact Sales","link":"\/contact"}]}',
                'order'     => 6,
            ],

            // ══════════════════════════════════════════
            // SPECIALITIES PAGE
            // ══════════════════════════════════════════
            [
                'page'      => 'specialities',
                'section'   => 'hero',
                'title'     => 'Specialty-Focused Medical Billing',
                'subtitle'  => 'Medical Billing Specialties',
                'content'   => 'We provide specialty-focused medical billing services across more than 75 medical specialties.',
                'image_url' => null,
                'metadata'  => '{"button_text": "Schedule Free Demo", "button_link": "\/contact", "meta_title": "Multi-Specialty Medical Billing Services | 50+ Specialties | DBillers", "meta_description": "Expert medical billing for 50+ specialties including Cardiology, Orthopedics, Anesthesia, and Behavioral Health. Reduce denials and increase cash flow with DBillers.", "meta_keywords": "multi-specialty billing, cardiology billing services, orthopedic RCM, anesthesia billing company, behavioral health billing, dermatology billing", "og_title": "Multi-Specialty Medical Billing | DBillers", "og_description": "Specialized RCM for 50+ medical specialties. Cardiology, Orthopedics, Anesthesia, and more."}',
                'order'     => 1,
            ],
            [
                'page'      => 'specialities',
                'section'   => 'popular_specialties',
                'title'     => 'Our Popular Specialties',
                'subtitle'  => null,
                'content'   => 'From cardiology to urgent care, our billers are trained in specialty-specific revenue cycle management.',
                'image_url' => null,
                'metadata'  => '{"specialties":[{"icon":"fa-heartbeat","name":"Cardiology"},{"icon":"fa-kidneys","name":"Urology"},{"icon":"fa-bone","name":"Orthopedics"},{"icon":"fa-brain","name":"Behavioral Health"},{"icon":"fa-microscope","name":"Laboratory Billing"},{"icon":"fa-truck-medical","name":"Urgent Care"},{"icon":"fa-stethoscope","name":"Primary Care"},{"icon":"fa-baby","name":"Pediatrics"},{"icon":"fa-allergies","name":"Dermatology"},{"icon":"fa-stomach","name":"Gastroenterology"},{"icon":"fa-nerve","name":"Neurology"},{"icon":"fa-female","name":"OB\/GYN"}]}',
                'order'     => 2,
            ],
            [
                'page'      => 'specialities',
                'section'   => 'not_listed',
                'title'     => "Couldn't Find Your Specialty Here?",
                'subtitle'  => "Don't worry. We serve over 75 specialties. Drop your email below and our medical billing manager will contact you shortly.",
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"button_text":"Contact Me","button_link":"\/contact"}',
                'order'     => 3,
            ],
            [
                'page'      => 'specialities',
                'section'   => 'final_cta',
                'title'     => 'Schedule a Free Demo',
                'subtitle'  => 'Sign up and book a free service demo',
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"buttons":[{"text":"Free Demo","link":"\/contact"},{"text":"See Pricing Packages","link":"\/contact"}]}',
                'order'     => 4,
            ],

            // ══════════════════════════════════════════
            // CONTACT PAGE
            // ══════════════════════════════════════════
            [
                'page'      => 'contact',
                'section'   => 'hero',
                'title'     => 'Contact Us',
                'subtitle'  => "We're Here to Help",
                'content'   => 'Have questions about our medical billing services? Ready to schedule a free demo? Fill out the form below and our team will get back to you within 24 hours.',
                'image_url' => null,
                'metadata'  => '{"button_text": "Get Started", "button_link": "#contact-form", "meta_title": "Contact DBillers | Free Consultation | Medical Billing Experts", "meta_description": "Contact DBillers for expert medical billing services. Get a free consultation and discover how we can maximize your practice revenue. Call or email us today.", "meta_keywords": "contact medical billing, free consultation, medical billing company near me, RCM services quote", "og_title": "Contact DBillers | Free Consultation", "og_description": "Schedule your free consultation with DBillers medical billing experts today."}',
                'order'     => 1,
            ],
            [
                'page'      => 'contact',
                'section'   => 'info',
                'title'     => 'Get in Touch',
                'subtitle'  => null,
                'content'   => null,
                'image_url' => null,
                'metadata'  => '{"phone":"(555) 123-4567","email":"info@dbillers.com","address":"123 Medical Center Drive, Suite 100, Los Angeles, CA 90001","hours":"Monday - Friday: 9:00 AM - 6:00 PM EST"}',
                'order'     => 2,
            ],
        ];

        foreach ($contents as $row) {
            DB::table('page_contents')->updateOrInsert(
                ['page' => $row['page'], 'section' => $row['section']],
                [
                    'title'     => $row['title'],
                    'subtitle'  => $row['subtitle'] ?? null,
                    'content'   => $row['content'] ?? null,
                    'image_url' => $row['image_url'] ?? null,
                    'metadata'  => $row['metadata'] ?? null,
                    'order'     => $row['order'],
                    'is_active' => true,
                    'updated_at' => now(),
                ]
            );
        }
    }
}
