---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/dbilphxf/public_html
    - /usr/local/bin/php $DEPLOY_PATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOY_PATH/artisan config:cache
    - /usr/local/bin/php $DEPLOY_PATH/artisan route:cache
    - /usr/local/bin/php $DEPLOY_PATH/artisan view:cache
