---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/dbilphxf/public_html
    - /bin/cp -R $DEPLOY_PATH/../dbillers-temp/* $DEPLOY_PATH/
    - cd $DEPLOY_PATH
    - /usr/local/bin/php composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan optimize
    - /usr/local/bin/php artisan migrate --force
